import { readFile, writeFile, mkdir } from 'fs/promises';
import { getEntityIndexPath, getEntitiesDir } from './paths.js';
import { listEntities } from './entities.js';
import type { EntityRecord } from './types.js';

const INDEX_HEADER = `# Entity Index
<!-- generated by housekeeping; derived from the entity files — do not edit -->

| Entity | Type | Scope | Summary | Last |
|--------|------|-------|---------|------|`;
const OMISSION_NOTICE = '_Additional entities omitted._';

export function lastTouched(record: EntityRecord): string {
  let latest = '';
  for (const observation of record.observations) {
    if (observation.touched && observation.touched > latest) latest = observation.touched;
  }
  return latest;
}

function indexRow(record: EntityRecord): string {
  const scope = record.repos.length ? `${record.scope}:${record.repos.join('/')}` : record.scope;
  const summary = (record.summary || record.displayName).replace(/\|/g, '\\|');
  return `| [[${record.entity}]] | ${record.type} | ${scope} | ${summary} | ${lastTouched(record) || '—'} |`;
}

export function renderIndex(records: EntityRecord[], characterBudget = Infinity): string {
  const rows = [...records]
    .sort((a, b) => {
      const touched = lastTouched(b).localeCompare(lastTouched(a));
      return touched !== 0 ? touched : a.entity.localeCompare(b.entity);
    })
    .map(indexRow);
  const complete = rows.length > 0 ? `${INDEX_HEADER}\n${rows.join('\n')}\n` : `${INDEX_HEADER}\n`;
  if (!Number.isFinite(characterBudget) || complete.length <= characterBudget) return complete;
  if (characterBudget < INDEX_HEADER.length + OMISSION_NOTICE.length + 2) return '';
  let rendered = `${INDEX_HEADER}\n`;
  let included = 0;
  for (let index = 0; index < rows.length; index++) {
    const row = `${rows[index]}\n`;
    const reserve = index < rows.length - 1 ? OMISSION_NOTICE.length + 1 : 0;
    if (rendered.length + row.length + reserve > characterBudget) break;
    rendered += row;
    included++;
  }
  if (included < rows.length) rendered += `${OMISSION_NOTICE}\n`;
  return rendered;
}

export async function rebuildIndex(): Promise<string> {
  const records = await listEntities();
  const markdown = renderIndex(records);
  await mkdir(getEntitiesDir(), { recursive: true });
  await writeFile(getEntityIndexPath(), markdown, 'utf-8');
  return markdown;
}

export async function readIndexMarkdown(): Promise<string> {
  try {
    return await readFile(getEntityIndexPath(), 'utf-8');
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return '';
    throw error;
  }
}
