/**
 * Entity Index + Push Selection
 *
 * `entities/index.md` is a thin, DERIVED table — one row per entity. It is
 * regenerated from the entity files (never hand-authored, never authoritative;
 * files win on conflict). It is always injected at spawn so an agent knows
 * what exists.
 *
 * Selection is PUSH: given the spawn context (repo/plugin + participating
 * users + task title) we deterministically pick which full entity pages to
 * inject — relevance-gated candidates only, one hop of wikilink expansion,
 * per-class budget ceilings. `search_memory` shares `tokenize`, so
 * pull-vs-push deltas indict budgets, not the scorer.
 */

import { readFile, writeFile, mkdir } from 'fs/promises';
import { getEntityIndexPath, getEntitiesDir, getEntityInjectMax, getOrgInjectMax } from './paths.js';
import { listEntities, resolveEntity } from './entities.js';
import type { EntityRecord, EntityScope } from './types.js';

const INDEX_HEADER = `# Entity Index
<!-- generated by housekeeping; derived from the entity files — do not edit -->

| Entity | Type | Scope | Summary | Last |
|--------|------|-------|---------|------|`;

// ============================================================================
// Derived index
// ============================================================================

/** Most-recent touched date across an entity's observations, or '' when none. */
export function lastTouched(record: EntityRecord): string {
  let latest = '';
  for (const o of record.observations) {
    if (o.touched && o.touched > latest) latest = o.touched;
  }
  return latest;
}

function indexRow(r: EntityRecord): string {
  const scope = r.repos.length ? `${r.scope}:${r.repos.join('/')}` : r.scope;
  const summary = (r.summary || r.displayName).replace(/\|/g, '\\|');
  return `| [[${r.entity}]] | ${r.type} | ${scope} | ${summary} | ${lastTouched(r) || '—'} |`;
}

/** Render the index Markdown for a set of records (newest-touched first). */
export function renderIndex(records: EntityRecord[]): string {
  const sorted = [...records].sort((a, b) => {
    const t = lastTouched(b).localeCompare(lastTouched(a));
    return t !== 0 ? t : a.entity.localeCompare(b.entity);
  });
  const rows = sorted.map(indexRow).join('\n');
  return rows ? `${INDEX_HEADER}\n${rows}\n` : `${INDEX_HEADER}\n`;
}

/**
 * Regenerate `entities/index.md` from the entity files. Derived artifact:
 * always reflects the files, overwriting any prior/manual content. Returns the
 * rendered Markdown.
 */
export async function rebuildIndex(): Promise<string> {
  const records = await listEntities();
  const md = renderIndex(records);
  await mkdir(getEntitiesDir(), { recursive: true });
  await writeFile(getEntityIndexPath(), md, 'utf-8');
  return md;
}

/** Read the persisted index Markdown, or '' when absent. */
export async function readIndexMarkdown(): Promise<string> {
  try {
    return await readFile(getEntityIndexPath(), 'utf-8');
  } catch (err: any) {
    if (err.code === 'ENOENT') return '';
    throw err;
  }
}

// ============================================================================
// Push selection
// ============================================================================

export interface SelectionContext {
  repo?: string;
  plugin?: string;
  users?: Array<{ userId: string; displayName: string }>;
  taskTitle?: string;
}

export interface SelectionResult {
  selected: EntityRecord[];
  dropped: string[];
  /** Per-selected telemetry in ranked order — feeds the spawn selection sensor. */
  selectedMeta: Array<{ slug: string; score: number; scope: EntityScope }>;
  /** Signal-bearing candidates before the budgets were applied. */
  candidates: number;
  /** Active pages with no relevance signal — never candidates, index-only. */
  zeroSignalExcluded: number;
}

const STOPWORDS = new Set([
  'a', 'an', 'and', 'or', 'the', 'of', 'in', 'on', 'at', 'to', 'for', 'with',
  'as', 'by', 'is', 'was', 'be', 'this', 'that', 'it', 'from', 'into',
]);

/**
 * Selection tokenizer — exported so the pull path (`search_memory`) ranks by
 * the same signal push selection scores by: a pull hit that push missed then
 * indicts budgets/context, never scorer skew.
 */
export function tokenize(s: string): Set<string> {
  return new Set(
    (s || '')
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, ' ')
      .split(/\s+/)
      .filter((t) => t.length > 2 && !STOPWORDS.has(t)),
  );
}

function recordTokens(r: EntityRecord): Set<string> {
  const parts = [r.entity.replace(/-/g, ' '), r.displayName, r.summary, r.domain, ...r.aliases];
  return tokenize(parts.join(' '));
}

const SCORE_REPO = 500;
const SCORE_OWNER = 200;
const SCORE_EXPANSION = 50;
const SCORE_PER_TOKEN = 10;

/**
 * Select full entity pages to inject for a spawn. Candidacy requires a
 * relevance signal (repo match, owned_by user, token overlap, one-hop
 * expansion). `orgMax` / `max` are independent ceilings for org / non-org
 * candidates, ranked by score then last-touched recency. Zero-signal pages
 * are neither injected nor in `dropped` ("qualified but over budget") —
 * the always-injected index keeps them discoverable.
 */
export function selectEntities(
  records: EntityRecord[],
  ctx: SelectionContext,
  max = getEntityInjectMax(),
  orgMax = getOrgInjectMax(),
): SelectionResult {
  const active = records.filter((r) => r.status !== 'archived');
  const ctxRepo = ctx.repo?.toLowerCase();
  const userIds = new Set((ctx.users ?? []).map((u) => u.userId.toLowerCase()));
  const ctxTokens = tokenize(
    [ctx.taskTitle, ctx.repo, ctx.plugin, ...(ctx.users ?? []).map((u) => u.displayName)].join(' '),
  );

  const scores = new Map<string, number>();
  const bySlug = new Map<string, EntityRecord>();
  for (const r of active) bySlug.set(r.entity, r);

  const bump = (slug: string, by: number) => scores.set(slug, (scores.get(slug) ?? 0) + by);

  for (const r of active) {
    if (ctxRepo && r.repos.some((repo) => repo.toLowerCase() === ctxRepo)) bump(r.entity, SCORE_REPO);
    if (userIds.size) {
      for (const rel of r.relations) {
        if (rel.type === 'owned_by' && userIds.has(rel.target.toLowerCase())) {
          bump(r.entity, SCORE_OWNER);
          break;
        }
      }
    }
    let overlap = 0;
    const tokens = recordTokens(r);
    for (const t of ctxTokens) if (tokens.has(t)) overlap++;
    if (overlap > 0) bump(r.entity, overlap * SCORE_PER_TOKEN);
  }

  // One-hop expansion: pull entities linked from any already-scored entity.
  for (const slug of Array.from(scores.keys())) {
    const r = bySlug.get(slug);
    if (!r) continue;
    for (const rel of r.relations) {
      const target = resolveEntity(rel.target, active);
      if (target && !scores.has(target.entity)) bump(target.entity, SCORE_EXPANSION);
    }
  }

  const candidates = Array.from(scores.keys())
    .map((slug) => bySlug.get(slug)!)
    .filter(Boolean);
  // Precompute last-touched once per candidate; a comparator runs O(n log n)
  // times and lastTouched() scans the whole observation list, so calling it
  // inside the comparator rescans each record's observations repeatedly.
  const lastTouchedBySlug = new Map(candidates.map((r) => [r.entity, lastTouched(r)]));
  const ranked = candidates.sort((a, b) => {
    const s = (scores.get(b.entity) ?? 0) - (scores.get(a.entity) ?? 0);
    if (s !== 0) return s;
    const t = (lastTouchedBySlug.get(b.entity) ?? '').localeCompare(lastTouchedBySlug.get(a.entity) ?? '');
    return t !== 0 ? t : a.entity.localeCompare(b.entity);
  });

  // Two independent budgets: `orgMax` bounds scope:org pages, `max` bounds the
  // rest. `ranked` is already ordered by score (relevance) then recency, so
  // taking the first that fit each budget yields the highest-scoring pages of
  // each class; the remainder are dropped (still discoverable via the index).
  const selected: EntityRecord[] = [];
  const selectedMeta: SelectionResult['selectedMeta'] = [];
  const dropped: string[] = [];
  let orgBudget = orgMax;
  let nonOrgBudget = max;
  for (const r of ranked) {
    const hasBudget = r.scope === 'org' ? orgBudget > 0 : nonOrgBudget > 0;
    if (hasBudget) {
      selected.push(r);
      selectedMeta.push({ slug: r.entity, score: scores.get(r.entity) ?? 0, scope: r.scope });
      if (r.scope === 'org') orgBudget--;
      else nonOrgBudget--;
    } else {
      dropped.push(r.entity);
    }
  }
  return {
    selected,
    dropped,
    selectedMeta,
    candidates: ranked.length,
    zeroSignalExcluded: active.length - ranked.length,
  };
}
