#!/bin/bash
# GIT_ASKPASS helper. Returns credentials for the active repo host (REPO_HOST).
#
# GitHub (default): username "x-access-token", password = GitHub App installation
#   token (generated by github-token.js).
# GitLab: username "oauth2", password = $GITLAB_TOKEN (group/project access token).

PROMPT="$1"
REPO_HOST="${REPO_HOST:-github}"

if [ "$REPO_HOST" = "gitlab" ]; then
  case "$PROMPT" in
    Username*) echo "oauth2" ;;
    Password*) echo "$GITLAB_TOKEN" ;;
  esac
else
  case "$PROMPT" in
    Username*)
      echo "x-access-token"
      ;;
    Password*)
      if [ -f /app/dist/scripts/github-token.js ]; then
        node /app/dist/scripts/github-token.js
      else
        npx tsx /app/scripts/github-token.ts
      fi
      ;;
  esac
fi
